### ISSUE TITLE
When lots of experiments have been already computed the terminal is a mess

### ISSUE THREAD

**Issue by alejandrofdez-us** [felescgon/best-epoch-selector#9]
https://github.com/felescgon/best-epoch-selector/blob/6610135fd24961af68df12973af03baed4417c58/helpers/similarity_ts_utils.py#L125

Can we show that the epoch is already computed in the general tqdm progress bar somehow?

**Comment by alejandrofdez-us** [comment]
<img width="1440" alt="Captura de pantalla 2023-08-01 a las 16 06 59" src="https://github.com/felescgon/best-epoch-selector/assets/19324988/f6aa9eaf-f3ec-4864-80b5-adc03f0f8376">
I wouldn't expect this ouput, but just the tqdm progress bar indicating that the epoch was skipped, not a new line every time an epoch result has been found.

**Comment by felescgon** [comment]
Added 'status' to progress bar in tqdm. It displays 'Computing...' when the current epoch metrics hasn't been found in the results.json file and 'Skipping...' in the other case.
The expected output from console now has the following format:
![image](https://github.com/felescgon/best-epoch-selector/assets/72603609/3804d41f-9d12-4005-b258-82f23507fd91)
